# Generated by Django 6.0.4 on 2026-04-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location_country',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='location.country')),
            ],
            options={
                'db_table': 'location_state',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='location.state')),
            ],
            options={
                'db_table': 'location_district',
            },
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('taluk_id', models.AutoField(primary_key=True, serialize=False)),
                ('taluk_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.CASCADE, related_name='taluks', to='location.district')),
            ],
            options={
                'db_table': 'location_taluk',
            },
        ),
    ]
