# Generated by Django 6.0.4 on 2026-04-24 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMaster',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(max_length=20, unique=True)),
                ('application_type', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_tamil', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhaar_no', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('student_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('parent_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Application_Master',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('Present', 'Present'), ('Permanent', 'Permanent'), ('Communication', 'Communication')], max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.country')),
                ('district', models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.district')),
                ('state', models.ForeignKey(blank=True, db_column='state_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.state')),
                ('taluk', models.ForeignKey(blank=True, db_column='taluk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.taluk')),
                ('application', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='application.applicationmaster')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('physically_challenged', models.BooleanField(default=False)),
                ('ex_serviceman_child', models.BooleanField(default=False)),
                ('tamil_origin', models.BooleanField(default=False)),
                ('sports_details', models.TextField(blank=True, null=True)),
                ('ncc_details', models.TextField(blank=True, null=True)),
                ('nss_details', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='application.applicationmaster')),
            ],
            options={
                'db_table': 'Additional_Info',
            },
        ),
        migrations.CreateModel(
            name='CoursePreference',
            fields=[
                ('course_pref_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_type', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('preference_order', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('application', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_preferences', to='application.applicationmaster')),
            ],
            options={
                'db_table': 'Course_Preference',
            },
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('father_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('application', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, related_name='parent_details', to='application.applicationmaster')),
            ],
            options={
                'db_table': 'Parent_Details',
            },
        ),
        migrations.CreateModel(
            name='PGAcademicRecord',
            fields=[
                ('pg_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('marks_obtained', models.IntegerField(blank=True, null=True)),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('month_year_of_passing', models.CharField(blank=True, max_length=20, null=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, related_name='pg_records', to='application.applicationmaster')),
            ],
            options={
                'db_table': 'PG_Academic_Record',
            },
        ),
        migrations.CreateModel(
            name='UGMarks',
            fields=[
                ('ug_marks_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('marks_secured', models.IntegerField(blank=True, null=True)),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('part', models.CharField(choices=[('Part I', 'Part I'), ('Part II', 'Part II'), ('Part III', 'Part III')], max_length=10)),
                ('application', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, related_name='ug_marks', to='application.applicationmaster')),
            ],
            options={
                'db_table': 'UG_Marks',
            },
        ),
    ]
