# Generated by Django 6.0.4 on 2026-04-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='additionalinfo',
            table='app_additional_info',
        ),
        migrations.AlterModelTable(
            name='address',
            table='app_address',
        ),
        migrations.AlterModelTable(
            name='applicationmaster',
            table='app_application_master',
        ),
        migrations.AlterModelTable(
            name='coursepreference',
            table='app_course_preference',
        ),
        migrations.AlterModelTable(
            name='parentdetails',
            table='app_parent_details',
        ),
        migrations.AlterModelTable(
            name='pgacademicrecord',
            table='app_pg_academic_record',
        ),
        migrations.AlterModelTable(
            name='ugmarks',
            table='app_ug_marks',
        ),
    ]
