# Generated by Django 6.0.4 on 2026-04-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_additionalinfo_table_alter_address_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='additionalinfo',
            table='application_additional_info',
        ),
        migrations.AlterModelTable(
            name='address',
            table='application_address',
        ),
        migrations.AlterModelTable(
            name='applicationmaster',
            table='application_application_master',
        ),
        migrations.AlterModelTable(
            name='coursepreference',
            table='application_course_preference',
        ),
        migrations.AlterModelTable(
            name='parentdetails',
            table='application_parent_details',
        ),
        migrations.AlterModelTable(
            name='pgacademicrecord',
            table='application_pg_academic_record',
        ),
        migrations.AlterModelTable(
            name='ugmarks',
            table='application_ug_marks',
        ),
    ]
