# Generated by Django 6.0.4 on 2026-04-24 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_additionalinfo_table_alter_address_table_and_more'),
    ]

    operations = [
        migrations.RunSQL("SET SESSION sql_require_primary_key = 0;"),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Documents Pending', 'Documents Pending'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Admitted', 'Admitted')], default='Under Review', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='application.applicationmaster')),
            ],
            options={
                'db_table': 'application_application_status',
            },
        ),
        migrations.RunSQL("SET SESSION sql_require_primary_key = 1;"),
    ]
