# Generated by Django 6.0.4 on 2026-04-24 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_applicationstatus'),
    ]

    operations = [
        migrations.RunSQL("SET SESSION sql_require_primary_key = 0;"),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_status_master',
            },
        ),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='status_id',
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='app_status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='application.statusmaster'),
        ),
        migrations.RunSQL("SET SESSION sql_require_primary_key = 1;"),
    ]
