# Generated by Django 6.0.4 on 2026-04-24 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_statusmaster_remove_applicationstatus_status_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMaster',
            fields=[
                ('community_id', models.AutoField(primary_key=True, serialize=False)),
                ('community_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_community_master',
            },
        ),
        migrations.AlterField(
            model_name='applicationmaster',
            name='community',
            field=models.ForeignKey(blank=True, db_column='community_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.communitymaster'),
        ),
    ]
