# Generated by Django 6.0.4 on 2026-04-24 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_communitymaster_alter_applicationmaster_community'),
        ('department', '0002_department_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepreference',
            name='department',
            field=models.ForeignKey(blank=True, db_column='dept_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
    ]
