# Generated by Django 6.0.4 on 2026-04-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_coursepreference_department'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicationmaster',
            table='application_master',
        ),
        migrations.AlterModelTable(
            name='applicationstatus',
            table='application_status',
        ),
        migrations.AlterModelTable(
            name='communitymaster',
            table='community_master',
        ),
        migrations.AlterModelTable(
            name='coursepreference',
            table='application_course',
        ),
        migrations.AlterModelTable(
            name='parentdetails',
            table='application_parent',
        ),
    ]
