# Generated by Django 6.0.4 on 2026-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_applicationmaster_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'applicant_users',
            },
        ),
    ]
