# Generated by Django 6.0.4 on 2026-04-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_applicantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
