# Generated by Django 6.0.4 on 2026-04-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_applicantuser_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicantuser',
            table='application_users',
        ),
    ]
