# Generated by Django 6.0.4 on 2026-04-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_applicantuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmaster',
            name='applicant_user',
            field=models.ForeignKey(blank=True, db_column='applicant_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application.applicantuser'),
        ),
    ]
