# Generated by Django 6.0.4 on 2026-04-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_applicationmaster_applicant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentdetails',
            old_name='father_income',
            new_name='annual_income',
        ),
        migrations.RemoveField(
            model_name='parentdetails',
            name='mother_income',
        ),
        migrations.AddField(
            model_name='parentdetails',
            name='father_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='parentdetails',
            name='guardian_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentdetails',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applicationmaster',
            name='application_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
