# Generated by Django 6.0.4 on 2026-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_rename_father_income_parentdetails_annual_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='other_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='other_taluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
