# Generated by Django 6.0.4 on 2026-04-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_address_other_district_address_other_taluk'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmaster',
            name='hsc_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationmaster',
            name='hsc_month_year_of_passing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationmaster',
            name='hsc_registration_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
