# Generated by Django 6.0.4 on 2026-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_applicationmaster_hsc_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugmarks',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
    ]
