# Generated by Django 6.0.4 on 2026-04-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='member_role',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='member_staff',
        ),
    ]
