# Generated by Django 6.0.4 on 2026-04-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_level'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department_department',
        ),
    ]
